# Generated by Django 3.2.9 on 2021-11-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorId', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movie_actors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('movieTitle', models.CharField(max_length=200)),
                ('movieYear', models.DateField(default='2021-12-12')),
                ('movieLanguage', models.IntegerField(choices=[(0, 'English'), (1, 'kinyarwanda'), (2, 'French')])),
                ('movieLogo', models.FileField(upload_to='video_logo')),
                ('movie_file', models.FileField(upload_to='videos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movieActor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieLibrary.actor')),
                ('movieGenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieLibrary.genre')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
