# Generated by Django 3.2.9 on 2021-11-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieLibrary', '0004_auto_20211129_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieLogo',
            field=models.ImageField(upload_to='movieLibrary/static/video_logo'),
        ),
    ]
