# Generated by Django 3.2.9 on 2021-11-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieLibrary', '0005_alter_movie_movielogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieLogo',
            field=models.ImageField(upload_to='video_logo/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
