# Generated by Django 3.2.9 on 2021-11-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieLibrary', '0007_auto_20211129_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieLogo',
            field=models.ImageField(upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(upload_to='img/%y'),
        ),
    ]
