# Generated by Django 3.2.9 on 2021-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieLibrary', '0008_auto_20211129_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieLanguage',
            field=models.IntegerField(choices=[('English', 'English'), ('kinyarwanda', 'kinyarwanda'), ('French', 'French')]),
        ),
    ]
