# Generated by Django 3.2.9 on 2021-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieLibrary', '0009_alter_movie_movielanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieLanguage',
            field=models.CharField(choices=[('English', 'English'), ('kinyarwanda', 'kinyarwanda'), ('French', 'French')], max_length=200),
        ),
    ]
